- name: pull the production repository
  ansible.builtin.git:
    repo: '{{ prod["repo"] }}'
    dest: '{{ prod["src"] }}'
    update: yes
    version: '{{ prod["branch"] }}'

- name: create dest directory
  ansible.builtin.file:
    path: '/tmp/session-counter'
    state: directory
    owner: pi
    group: pi
    mode: u=rwx,g=rx,o=rx
  become: yes

- name: copy in session-counter
  ansible.builtin.command:
    cmd: >
      cp 
      '{{ dist }}/session-counter.tgz'
      '{{ prod["src"] }}/roles/session-counter/files/session-counter.tgz'

- name: add file 
  ansible.builtin.command:
    chdir: '{{ prod["src"] }}'
    cmd: >
      git add 
      '{{ prod["src"] }}/roles/session-counter/files/session-counter.tgz'

- name: commit file
  ansible.builtin.command:
    chdir: '{{ prod["src"] }}'
    cmd: git commit -am "adding release product session-counter.tgz for tag {{ commit }}"

- name: push commit
  ansible.builtin.command:
    chdir: '{{ prod["src"] }}'
    cmd: git push
